        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 22 21:16:49 2017
        MODULE CHECK_CONVERGENCE__genmod
          INTERFACE 
            SUBROUTINE CHECK_CONVERGENCE
            END SUBROUTINE CHECK_CONVERGENCE
          END INTERFACE 
        END MODULE CHECK_CONVERGENCE__genmod
