        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 22 21:16:49 2017
        MODULE INFLUENCE_COEFFICIENT__genmod
          INTERFACE 
            SUBROUTINE INFLUENCE_COEFFICIENT
            END SUBROUTINE INFLUENCE_COEFFICIENT
          END INTERFACE 
        END MODULE INFLUENCE_COEFFICIENT__genmod
