        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 22 21:16:49 2017
        MODULE INITIAL__genmod
          INTERFACE 
            SUBROUTINE INITIAL
            END SUBROUTINE INITIAL
          END INTERFACE 
        END MODULE INITIAL__genmod
