        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 22 21:16:49 2017
        MODULE OUTPUT__genmod
          INTERFACE 
            SUBROUTINE OUTPUT
            END SUBROUTINE OUTPUT
          END INTERFACE 
        END MODULE OUTPUT__genmod
